events {
    worker_connections 1024;
}

http {
    resolver kube-dns.kube-system.svc.cluster.local valid=10s;

    server {
        listen 80;
        server_name _;

        location /health {
            return 200 '{\"status\":\"healthy\",\"service\":\"api-gateway\"}';
            add_header Content-Type application/json;
        }

        location /restaurants {
            proxy_pass http://restaurant-service.swiggyops.svc.cluster.local:8002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /orders {
            proxy_pass http://order-service.swiggyops.svc.cluster.local:8003;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /deliveries {
            proxy_pass http://delivery-service.swiggyops.svc.cluster.local:8004;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /drivers {
            proxy_pass http://delivery-service.swiggyops.svc.cluster.local:8004;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /payments {
            proxy_pass http://payment-service.swiggyops.svc.cluster.local:8005;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /notifications {
            proxy_pass http://notification-service.swiggyops.svc.cluster.local:8006;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            return 200 '{\"service\":\"SwiggyOps API Gateway\",\"version\":\"1.0\"}';
            add_header Content-Type application/json;
        }
    }
}
