events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name _;

        location /health {
            return 200 '{"status":"healthy","service":"api-gateway"}';
            add_header Content-Type application/json;
        }

        location /restaurants {
            set $upstream restaurant-service.swiggyops.svc.cluster.local:8002;
            proxy_pass http://$upstream;
            proxy_set_header Host $host;
        }

        location /orders {
            set $upstream order-service.swiggyops.svc.cluster.local:8003;
            proxy_pass http://$upstream;
            proxy_set_header Host $host;
        }

        location /deliveries {
            set $upstream delivery-service.swiggyops.svc.cluster.local:8004;
            proxy_pass http://$upstream;
            proxy_set_header Host $host;
        }

        location /payments {
            set $upstream payment-service.swiggyops.svc.cluster.local:8005;
            proxy_pass http://$upstream;
            proxy_set_header Host $host;
        }

        location /notifications {
            set $upstream notification-service.swiggyops.svc.cluster.local:8006;
            proxy_pass http://$upstream;
            proxy_set_header Host $host;
        }

        location / {
            return 200 '{"service":"SwiggyOps API Gateway","version":"1.0"}';
            add_header Content-Type application/json;
        }
    }
}